name: teknik_servis

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0

  image_painter: ^0.7.1

   


  fl_chart: ^0.66.0
  image: ^4.1.7

  permission_handler: ^11.3.0

  



  

  shared_preferences: ^2.2.3

  path_provider: ^2.1.2

  pdf: ^3.10.8
  
  share_plus: ^7.2.1

  signature: ^5.4.0
  image_picker: ^1.0.7
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto-VariableFont_wdth,wght.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Regular.ttf
    - assets/icon/app_icon.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path:  "assets/icon/app_icon.png"